export const questionDB = [
  {q:"Wie heißt Lukes Heimatplanet?",a:["Tatooine","Naboo","Hoth","Endor"],c:0},
  {q:"Welche Farbe hat Mace Windus Lichtschwert?",a:["Blau","Grün","Lila","Gelb"],c:2},
  {q:"Wer ist der Vater von Luke Skywalker?",a:["Obi-Wan Kenobi","Darth Vader","Yoda","Palpatine"],c:1},
  {q:"Wie lautet der vollständige Name von R2-D2s Begleiter?",a:["C-3PX","C-3PO","K-3PO","L-3PO"],c:1},
  {q:"Auf welchem Planeten lebt Yoda im Exil?",a:["Coruscant","Tatooine","Dagobah","Endor"],c:2},
  {q:"Welches Raumschiff pilotiert Han Solo?",a:["X-Wing","TIE Fighter","Millennium Falcon","Star Destroyer"],c:2},
  {q:"Wie heißt Darth Vaders ursprünglicher Name?",a:["Anakin Skywalker","Ben Solo","Qui-Gon Jinn","Mace Windu"],c:0},
  {q:"Was ist die Macht (The Force)?",a:["Eine Waffe","Eine Energie, die alles verbindet","Ein Raumschiff","Ein Planet"],c:1},
  {q:"Welche Farbe hat Lukes erstes Lichtschwert?",a:["Blau","Grün","Rot","Lila"],c:0},
  {q:"Wer spricht den berühmten Satz: 'Ich bin dein Vater'?",a:["Yoda","Obi-Wan","Darth Vader","Palpatine"],c:2},
  {q:"Wie heißt der Anführer der Rebellion?",a:["Prinzessin Leia","Han Solo","Luke Skywalker","Mon Mothma"],c:0},
  {q:"Welcher Planet wird im ersten Film durch den Todesstern zerstört?",a:["Alderaan","Naboo","Coruscant","Mandalore"],c:0},
  {q:"Wie heißt Chewbaccas Spezies?",a:["Ewok","Gungan","Wookiee","Twi'lek"],c:2},
  {q:"In welchem Film erscheint Jabba the Hutt zum ersten Mal physisch?",a:["Episode IV","Episode V","Episode VI","Episode I"],c:2},
  {q:"Welches Tier reitet Luke auf dem Planeten Hoth?",a:["Bantha","Tauntaun","Rancor","Wampa"],c:1},
  {q:"Wie lautet der Orden der Hüter der Macht?",a:["Sith","Jedi","Mandalorianer","Graue"],c:1},
  {q:"Was ist der Name von Darth Vaders Sternenzerstörer?",a:["Death Star","Executor","Devastator","Chimaera"],c:1},
  {q:"Welcher Planet ist die Heimatwelt der Ewoks?",a:["Endor (Mond)","Naboo","Tatooine","Mustafar"],c:0},
  {q:"Wer tötet Han Solo?",a:["Darth Vader","Kylo Ren","Captain Phasma","Snoke"],c:1},
  {q:"Wie heißt Obi-Wan Kenobis Meister?",a:["Yoda","Mace Windu","Qui-Gon Jinn","Count Dooku"],c:2},
  {q:"Was ist BB-8?",a:["Ein Astromechdroide","Ein Protokolldroide","Ein Kampfdroide","Ein Medizindroide"],c:0},
  {q:"Auf welchem Planeten findet der finale Kampf in Rogue One statt?",a:["Scarif","Jedha","Eadu","Mustafar"],c:0},
  {q:"Wie heißt der Mandalorier in der gleichnamigen Serie?",a:["Din Djarin","Bo-Katan","Paz Vizsla","Boba Fett"],c:0},
  {q:"Welche Waffe benutzen Stormtrooper?",a:["Blasenpistole","E-11 Blaster","DL-44","DC-15"],c:1},
  {q:"Wie heißt der erste Todesstern-Direktor?",a:["Grand Moff Tarkin","Darth Vader","Admiral Ozzel","General Veers"],c:0},
  {q:"Welche Farbe haben Sith-Schwerter?",a:["Rot","Blau","Grün","Gelb"],c:0},
  {q:"Wie heißt Luke Skywalkers Heimatplanet?",a:["Tatooine","Naboo","Alderaan","Corellia"],c:0},
  {q:"Wer ist Lukes Vater?",a:["Obi-Wan Kenobi","Darth Vader","Yoda","Han Solo"],c:1},
  {q:"Wie heißt der Astromech-Droide von Anakin und Luke?",a:["C-3PO","R2-D2","BB-8","K-2SO"],c:1},
  {q:"Wer schmuggelt Luke und Obi-Wan nach Alderaan?",a:["Lando Calrissian","Han Solo","Boba Fett","Wedge Antilles"],c:1},
  {q:"Wie heißt das Schiff von Han Solo?",a:["Ghost","Millennium Falcon","Razor Crest","Slave I"],c:1},
  {q:"Welche Spezies ist Chewbacca?",a:["Ewok","Wookiee","Rodian","Mon Calamari"],c:1},
  {q:"Wie heißt der Imperator?",a:["Palpatine","Tarkin","Thrawn","Snoke"],c:0},
  {q:"Wie heißt Darth Vaders echter Name?",a:["Anakin Skywalker","Ben Solo","Revan","Galen Marek"],c:0},
  {q:"Welche Organisation bewacht Frieden und Gerechtigkeit?",a:["Die Sith","Die Jedi","Die Hutts","Die Mandalorianer"],c:1},
  {q:"Wie heißt der Planet der Wookiees?",a:["Kashyyyk","Endor","Kamino","Mustafar"],c:0},
  {q:"Wer trainiert Luke auf Dagobah?",a:["Obi-Wan","Yoda","Mace Windu","Qui-Gon"],c:1},
  {q:"Wie heißt der Kopfgeldjäger mit Mandalorianer-Rüstung im Original?",a:["Jango Fett","Boba Fett","Din Djarin","Bo-Katan"],c:1},
  {q:"Wie heißt Lukes Schwester?",a:["Padmé","Leia","Jyn","Rey"],c:1},
  {q:"Wer zerstört den ersten Todesstern?",a:["Han Solo","Luke Skywalker","Wedge Antilles","Lando"],c:1},
  {q:"Welcher Planet wird vom Todesstern zerstört?",a:["Alderaan","Hoth","Naboo","Coruscant"],c:0},
  {q:"Wie heißt der Eisplanet in Episode V?",a:["Ilum","Hoth","Jedha","Dantooine"],c:1},
  {q:"Wie heißt Darth Vaders Flaggschiff?",a:["Executor","Devastator","Chimaera","Supremacy"],c:0},
  {q:"Wie heißt der Planet der Klonarmee?",a:["Kamino","Geonosis","Felucia","Utapau"],c:0},
  {q:"Wer erschafft die Klonarmee?",a:["Dooku","Sifo-Dyas","Palpatine","Jango"],c:1},
  {q:"Wer spielt Anakin in Episode III?",a:["Hayden Christensen","Ewan McGregor","Mark Hamill","Adam Driver"],c:0},
  {q:"Wie heißt Anakins Mutter?",a:["Padmé","Shmi","Leia","Beru"],c:1},
  {q:"Wer ist Anakins Padawan in The Clone Wars?",a:["Ahsoka Tano","Barriss Offee","Rey","Sabine Wren"],c:0},
  {q:"Wie heißt der Planet der Gungans?",a:["Naboo","Corellia","Onderon","Ryloth"],c:0},
  {q:"Wer ist der Sith-Meister von Darth Maul?",a:["Palpatine","Dooku","Plagueis","Vader"],c:0},
  {q:"Welche Waffe benutzt Darth Maul?",a:["Doppelklingen-Lichtschwert","Axt","Blaster","Speer"],c:0},
  {q:"Wie heißt der Jedi-Rat-Saal Planet?",a:["Coruscant","Naboo","Kashyyyk","Utapau"],c:0},
  {q:"Wer ist der Meister von Obi-Wan?",a:["Yoda","Qui-Gon Jinn","Windu","Dooku"],c:1},
  {q:"Wie heißt der Planet mit Lava aus Episode III?",a:["Mustafar","Jedha","Ilum","Exegol"],c:0},
  {q:"Wer besiegt Darth Maul in Episode I?",a:["Qui-Gon","Obi-Wan","Anakin","Yoda"],c:1},
  {q:"Wie heißt die Hauptstadt der Republik?",a:["Coruscant","Alderaan","Corellia","Naboo"],c:0},
  {q:"Wer führt die Separatisten an?",a:["Darth Sidious","Count Dooku","Grievous","Nute Gunray"],c:1},
  {q:"Wie heißt General Grievous Spezies?",a:["Kaleesh","Zabrak","Chiss","Trandoshan"],c:0},
  {q:"Welche Droiden kämpfen für die Separatisten?",a:["B1 Battle Droids","Stormtrooper","Dark Trooper","KX Droid"],c:0},
  {q:"Wie heißen die Elite-Klone von Palpatine?",a:["ARC Trooper","Praetorian Guard","Royal Guard","Death Trooper"],c:2},
  {q:"Welche Farbe hat Mace Windus Lichtschwert?",a:["Blau","Grün","Lila","Gelb"],c:2},
  {q:"Wer tötet Mace Windu?",a:["Anakin","Palpatine","Dooku","Vader"],c:1},
  {q:"Wie heißt der Wüstenplanet von Boba Fett Serie?",a:["Tatooine","Jakku","Geonosis","Jedha"],c:0},
  {q:"Wie heißt Reys Planet?",a:["Jakku","Tatooine","Corellia","Endor"],c:0},
  {q:"Wie heißt Kylo Rens echter Name?",a:["Ben Solo","Jacen Solo","Cade Skywalker","Anakin Solo"],c:0},
  {q:"Wer ist Kylo Rens Vater?",a:["Luke","Han Solo","Lando","Wedge"],c:1},
  {q:"Wie heißt die Widerstands-Generalin?",a:["Leia Organa","Holdo","Jyn Erso","Mon Mothma"],c:0},
  {q:"Wie heißt der Planet mit der Starkiller Base?",a:["Ilum","Exegol","Crait","Jedha"],c:0},
  {q:"Wer baut den Todesstern?",a:["Geonosianer","Hutts","Bothaner","Chiss"],c:0},
  {q:"Wie heißt der Planet mit der roten Salzoberfläche?",a:["Crait","Hoth","Ilum","Jedha"],c:0},
  {q:"Wie heißt das Schiff von Din Djarin ursprünglich?",a:["Razor Crest","Falcon","Ghost","Slave I"],c:0},
  {q:"Wie heißt das Kind von Yodas Spezies in Mandalorian?",a:["Grogu","Yaddle","Minch","Oteg"],c:0},
  {q:"Wie heißt die Rebellenbasis in Rogue One?",a:["Yavin 4","Hoth","Endor","Dantooine"],c:0},
  {q:"Wer stiehlt die Todesstern-Pläne?",a:["Jyn Erso","Leia","Cassian","Bodhi"],c:0},
  {q:"Wie heißt der Pilot von Rogue One?",a:["Bodhi Rook","Poe Dameron","Wedge","Biggs"],c:0},
  {q:"Wie heißt der Imperiale Wissenschaftler in Rogue One?",a:["Galen Erso","Krennic","Tarkin","Hux"],c:0},
  {q:"Wer ist Director Krennic?",a:["Todesstern Leiter","Jedi","Rebell","Schmuggler"],c:0},
  {q:"Wie heißt der Planet Jedha?",a:["Heilige Jedi Welt","Hutt Planet","Klon Planet","Imperial Hauptstadt"],c:0},
  {q:"Welche Kreatur lebt auf Endor?",a:["Ewoks","Jawas","Tusken","Wookiees"],c:0},
  {q:"Wer führt die Ewoks?",a:["Wicket","Logray","Chirpa","Paploo"],c:2},
  {q:"Wie heißt die Mandalorianische Hauptstadt?",a:["Sundari","Keldabe","Concordia","Krownest"],c:0},
  {q:"Wer ist Mandalore in Clone Wars?",a:["Duchess Satine","Bo-Katan","Ursa","Sabine"],c:0},
  {q:"Wer tötet Satine?",a:["Maul","Obi-Wan","Dooku","Vader"],c:0},
  {q:"Wie heißt die Spezies von Jar Jar?",a:["Gungan","Rodian","Toydarian","Kaminoan"],c:0},
  {q:"Wie heißt Watto Spezies?",a:["Toydarian","Rodian","Hutt","Twi'lek"],c:0},
  {q:"Welche Spezies ist Jabba?",a:["Hutt","Gamorreaner","Trandoshan","Nikto"],c:0},
  {q:"Wer ist Jabbas Tänzerin?",a:["Oola","Leia","Ayla","Lyn"],c:0},
  {q:"Wie heißt Boba Fetts Schiff?",a:["Slave I","Razor Crest","Ghost","Falcon"],c:0},
  {q:"Wie heißt Jango Fetts Sohn?",a:["Boba","Cade","Rex","Fenn"],c:0},
  {q:"Wer ist Captain Rex?",a:["Klon","Jedi","Sith","Schmuggler"],c:0},
  {q:"Wie heißt Anakins Sternjäger Typ?",a:["Eta-2","X-Wing","A-Wing","Y-Wing"],c:0},
  {q:"Wie heißt Luke's Fighter?",a:["X-Wing","A-Wing","TIE","B-Wing"],c:0},
  {q:"Wie heißen Imperiale Jäger?",a:["TIE Fighter","ARC","Z95","V-Wing"],c:0},
  {q:"Wie heißt Palpatines Sith Name?",a:["Darth Sidious","Darth Tyranus","Darth Bane","Darth Nihilus"],c:0},
  {q:"Wie heißt Dookus Sith Name?",a:["Darth Tyranus","Darth Plagueis","Darth Revan","Darth Malak"],c:0},
  {q:"Wie heißt der Mond von Endor offiziell?",a:["Endor II","Forest Moon of Endor","Sanctuary Moon","Dxun"],c:2},
  {q:"Wie lautet der echte Name von Count Dooku?",a:["Dooku Tyranus","Dooku Serenno","Tyranus Valorum","Dooku Corvin"],c:1},
  {q:"Welcher Schauspieler spielte den Kopfgeldjäger Dengar in Episode V?",a:["Jeremy Bulloch","Alan Harris","Morris Bush","Mark Austin"],c:2},
  {q:"Wie heißt der Heimatplanet von Grand Admiral Thrawn?",a:["Csilla","Chiss Prime","Ilum","Mygeeto"],c:0},
  {q:"Welche Spezies ist Admiral Ackbar?",a:["Quarren","Mon Calamari","Nautolan","Aqualish"],c:1},
  {q:"Welcher Planet wurde von der Starkiller Base zerstört?",a:["Hosnian Prime","Chandrila","Corellia","Kuat"],c:0},
  {q:"Wie heißt die Bar von Maz Kanata?",a:["Maz Castle","Kanata Cantina","Takodana Lodge","Maz's Castle"],c:3},
  {q:"Welches Tier reitet Luke auf Hoth?",a:["Bantha","Tauntaun","Dewback","Wampa"],c:1},
  {q:"Wie lautet der Code des Gefangenen, den Leia in Episode IV vorgibt?",a:["TK-421","AA-23","BH-1138","TK-1138"],c:3},
  {q:"Wer löschte die Jedi-Archive laut Jocasta Nu angeblich nicht?",a:["Ein Jedi","Ein Droide","Niemand","Ein Padawan"],c:0},
  {q:"Welcher Planet ist die Heimat der Klon-Armee?",a:["Kamino","Geonosis","Saleucami","Umbara"],c:0},
  {q:"Wie heißt der Kommandant des Todessterns in Episode IV?",a:["Tarkin","Tagge","Piett","Jerjerrod"],c:0},
  {q:"Wie viele Systeme umfasst der Mid Rim ungefähr laut Kanon?",a:["100","1000","10.000","50.000"],c:2},
  {q:"Welche Farbe hat Mace Windus Lichtschwert?",a:["Blau","Grün","Lila","Gelb"],c:2},
  {q:"Welches Droidenmodell ist K-2SO?",a:["IG-Serie","KX-Serie","BX-Serie","HK-Serie"],c:1},
  {q:"Wer trainierte Qui-Gon Jinn?",a:["Dooku","Yoda","Windu","Kenobi"],c:0},
  {q:"Wie heißt Boba Fetts Schiff?",a:["Slave I","Razor Crest","Hound's Tooth","Firespray"],c:0},
  {q:"Auf welchem Planeten wurde Order 66 an Ki-Adi-Mundi vollstreckt?",a:["Felucia","Mygeeto","Cato Neimoidia","Utapau"],c:1},
  {q:"Welche Spezies ist Jar Jar Binks?",a:["Gungan","Toydarian","Nautolan","Rodian"],c:0},
  {q:"Wie heißt der Planet aus dem Obi-Wan gegen Anakin Finale?",a:["Mustafar","Sullust","Ryloth","Malachor"],c:0},
  {q:"Wer war der erste Offizier, der Darth Vader in Episode V direkt widerspricht?",a:["Piett","Ozzel","Needa","Veers"],c:1},
  {q:"Wie heißt Chewbaccas Heimatplanet?",a:["Kashyyyk","Trandosha","Endor","Bothawui"],c:0},
  {q:"Welche Organisation baute den ersten Todesstern laut Rogue One?",a:["Imperial Engineering Corps","Imperial Department of Military Research","Advanced Weapons Division","Imperial Science Bureau"],c:1},
  {q:"Wie heißt der Kristall in einem Lichtschwert?",a:["Kyber","Ilum","Kessel","Nova"],c:0},
  {q:"Wer war der Pilot von Red Five vor Luke?",a:["Biggs Darklighter","Wedge Antilles","Garven Dreis","Jek Porkins"],c:2},
  {q:"Welcher Planet ist bekannt für Gewürzabbau?",a:["Kessel","Naboo","Corellia","Dantooine"],c:0},
  {q:"Wie heißt der Sith-Name von Palpatine?",a:["Darth Tenebrous","Darth Plagueis","Darth Sidious","Darth Bane"],c:2},
  {q:"Wer baut C-3PO ursprünglich?",a:["Anakin Skywalker","Watto","Padmé","Bail Organa"],c:0},
  {q:"Wie heißt das Wurmmonster im Asteroiden in Episode V?",a:["Exogorth","Sarlacc","Krayt","Mynock"],c:0},
  {q:"Welcher Planet ist Lando Calrissians Stadt?",a:["Bespin","Ord Mantell","Nal Hutta","Batuu"],c:0},
  {q:"Wer tötet Count Dooku?",a:["Anakin","Obi-Wan","Yoda","Palpatine"],c:0},
  {q:"Wie heißt der Planet der Clones Ausbildung?",a:["Kamino","Geonosis","Saleucami","Mygeeto"],c:0},
  {q:"Wie heißt die Republik Armee?",a:["Grand Army of the Republic","Stormtroopers","Imperial Navy","First Order"],c:0},
  {q:"Was sind Midi-Chlorianer?",a:["Machtorganismen","Droiden","Kristalle","Alienart"],c:0},
  {q:"Welcher Kristall fokussiert Lichtschwerter?",a:["Kyber","Kaiburr","Ilum","Barab"],c:0},
  {q:"Wo finden Jedi oft Kyber Kristalle?",a:["Ilum","Mustafar","Endor","Naboo"],c:0},
  {q:"Wer gründet die Rebellion?",a:["Mon Mothma","Leia","Bail Organa","Saw Gerrera"],c:0},
  {q:"Wie heißt Leia’s Vater?",a:["Bail Organa","Han Solo","Tarkin","Palpatine"],c:0},
  {q:"Wie heißt der Planet Alderaan?",a:["Leias Heimat","Jedi Tempel","Sith Welt","Klon Planet"],c:0},
  {q:"Wer zerstört den zweiten Todesstern?",a:["Lando Calrissian","Han Solo","Luke","Wedge"],c:0}
];
