export const questionDB = [
  {q:"What is Luke's home planet called?",a:["Tatooine","Naboo","Hoth","Endor"],c:0},
  {q:"What color is Mace Windu's lightsaber?",a:["Blue","Green","Purple","Yellow"],c:2},
  {q:"Who is Luke Skywalker's father?",a:["Obi-Wan Kenobi","Darth Vader","Yoda","Palpatine"],c:1},
  {q:"What is the full name of R2-D2's companion?",a:["C-3PX","C-3PO","K-3PO","L-3PO"],c:1},
  {q:"On which planet does Yoda live in exile?",a:["Coruscant","Tatooine","Dagobah","Endor"],c:2},
  {q:"Which spaceship does Han Solo pilot?",a:["X-Wing","TIE Fighter","Millennium Falcon","Star Destroyer"],c:2},
  {q:"What was Darth Vader's original name?",a:["Anakin Skywalker","Ben Solo","Qui-Gon Jinn","Mace Windu"],c:0},
  {q:"What is the Force?",a:["A weapon","An energy that binds everything together","A spaceship","A planet"],c:1},
  {q:"What color is Luke's first lightsaber?",a:["Blue","Green","Red","Purple"],c:0},
  {q:"Who says the famous line 'I am your father'?",a:["Yoda","Obi-Wan","Darth Vader","Palpatine"],c:2},
  {q:"Who is the leader of the Rebellion?",a:["Princess Leia","Han Solo","Luke Skywalker","Mon Mothma"],c:0},
  {q:"Which planet is destroyed by the Death Star in the first film?",a:["Alderaan","Naboo","Coruscant","Mandalore"],c:0},
  {q:"What species is Chewbacca?",a:["Ewok","Gungan","Wookiee","Twi'lek"],c:2},
  {q:"In which film does Jabba the Hutt appear physically for the first time?",a:["Episode IV","Episode V","Episode VI","Episode I"],c:2},
  {q:"What animal does Luke ride on the planet Hoth?",a:["Bantha","Tauntaun","Rancor","Wampa"],c:1},
  {q:"What is the order of Force guardians called?",a:["Sith","Jedi","Mandalorians","The Grey"],c:1},
  {q:"What is the name of Darth Vader's Star Destroyer?",a:["Death Star","Executor","Devastator","Chimaera"],c:1},
  {q:"Which planet is the homeworld of the Ewoks?",a:["Endor (moon)","Naboo","Tatooine","Mustafar"],c:0},
  {q:"Who kills Han Solo?",a:["Darth Vader","Kylo Ren","Captain Phasma","Snoke"],c:1},
  {q:"What is the name of Obi-Wan Kenobi's master?",a:["Yoda","Mace Windu","Qui-Gon Jinn","Count Dooku"],c:2},
  {q:"What is BB-8?",a:["An astromech droid","A protocol droid","A battle droid","A medical droid"],c:0},
  {q:"On which planet does the final battle in Rogue One take place?",a:["Scarif","Jedha","Eadu","Mustafar"],c:0},
  {q:"What is the name of the Mandalorian in the series?",a:["Din Djarin","Bo-Katan","Paz Vizsla","Boba Fett"],c:0},
  {q:"Which weapon do Stormtroopers use?",a:["Blaster pistol","E-11 blaster","DL-44","DC-15"],c:1},
  {q:"What is the name of the first Death Star director?",a:["Grand Moff Tarkin","Darth Vader","Admiral Ozzel","General Veers"],c:0},
  {q:"What color are Sith lightsabers?",a:["Red","Blue","Green","Yellow"],c:0},
  {q:"What is Luke Skywalker's home planet?",a:["Tatooine","Naboo","Alderaan","Corellia"],c:0},
  {q:"Who is Luke's father?",a:["Obi-Wan Kenobi","Darth Vader","Yoda","Han Solo"],c:1},
  {q:"What is the name of Anakin and Luke's astromech droid?",a:["C-3PO","R2-D2","BB-8","K-2SO"],c:1},
  {q:"Who smuggles Luke and Obi-Wan to Alderaan?",a:["Lando Calrissian","Han Solo","Boba Fett","Wedge Antilles"],c:1},
  {q:"What is Han Solo's ship called?",a:["Ghost","Millennium Falcon","Razor Crest","Slave I"],c:1},
  {q:"What species is Chewbacca?",a:["Ewok","Wookiee","Rodian","Mon Calamari"],c:1},
  {q:"What is the name of the Emperor?",a:["Palpatine","Tarkin","Thrawn","Snoke"],c:0},
  {q:"What is Darth Vader's real name?",a:["Anakin Skywalker","Ben Solo","Revan","Galen Marek"],c:0},
  {q:"Which organization guards peace and justice?",a:["The Sith","The Jedi","The Hutts","The Mandalorians"],c:1},
  {q:"What is the name of the Wookiee planet?",a:["Kashyyyk","Endor","Kamino","Mustafar"],c:0},
  {q:"Who trains Luke on Dagobah?",a:["Obi-Wan","Yoda","Mace Windu","Qui-Gon"],c:1},
  {q:"What is the name of the bounty hunter with Mandalorian armor in the original trilogy?",a:["Jango Fett","Boba Fett","Din Djarin","Bo-Katan"],c:1},
  {q:"What is Luke's sister called?",a:["Padmé","Leia","Jyn","Rey"],c:1},
  {q:"Who destroys the first Death Star?",a:["Han Solo","Luke Skywalker","Wedge Antilles","Lando"],c:1},
  {q:"Which planet is destroyed by the Death Star?",a:["Alderaan","Hoth","Naboo","Coruscant"],c:0},
  {q:"What is the ice planet in Episode V called?",a:["Ilum","Hoth","Jedha","Dantooine"],c:1},
  {q:"What is Darth Vader's flagship called?",a:["Executor","Devastator","Chimaera","Supremacy"],c:0},
  {q:"What is the planet of the clone army?",a:["Kamino","Geonosis","Felucia","Utapau"],c:0},
  {q:"Who creates the clone army?",a:["Dooku","Sifo-Dyas","Palpatine","Jango"],c:1},
  {q:"Who plays Anakin in Episode III?",a:["Hayden Christensen","Ewan McGregor","Mark Hamill","Adam Driver"],c:0},
  {q:"What is Anakin's mother's name?",a:["Padmé","Shmi","Leia","Beru"],c:1},
  {q:"Who is Anakin's Padawan in The Clone Wars?",a:["Ahsoka Tano","Barriss Offee","Rey","Sabine Wren"],c:0},
  {q:"What is the planet of the Gungans?",a:["Naboo","Corellia","Onderon","Ryloth"],c:0},
  {q:"Who is the Sith master of Darth Maul?",a:["Palpatine","Dooku","Plagueis","Vader"],c:0},
  {q:"What weapon does Darth Maul use?",a:["Double-bladed lightsaber","Axe","Blaster","Spear"],c:0},
  {q:"On which planet is the Jedi Council chamber located?",a:["Coruscant","Naboo","Kashyyyk","Utapau"],c:0},
  {q:"Who is Obi-Wan's master?",a:["Yoda","Qui-Gon Jinn","Windu","Dooku"],c:1},
  {q:"What is the lava planet in Episode III?",a:["Mustafar","Jedha","Ilum","Exegol"],c:0},
  {q:"Who defeats Darth Maul in Episode I?",a:["Qui-Gon","Obi-Wan","Anakin","Yoda"],c:1},
  {q:"What is the capital of the Republic?",a:["Coruscant","Alderaan","Corellia","Naboo"],c:0},
  {q:"Who leads the Separatists?",a:["Darth Sidious","Count Dooku","Grievous","Nute Gunray"],c:1},
  {q:"What species is General Grievous?",a:["Kaleesh","Zabrak","Chiss","Trandoshan"],c:0},
  {q:"Which droids fight for the Separatists?",a:["B1 Battle Droids","Stormtroopers","Dark Troopers","KX Droids"],c:0},
  {q:"What are Palpatine's elite guards called?",a:["ARC Troopers","Praetorian Guard","Royal Guard","Death Troopers"],c:2},
  {q:"What color is Mace Windu's lightsaber?",a:["Blue","Green","Purple","Yellow"],c:2},
  {q:"Who kills Mace Windu?",a:["Anakin","Palpatine","Dooku","Vader"],c:1},
  {q:"What is the desert planet in The Book of Boba Fett?",a:["Tatooine","Jakku","Geonosis","Jedha"],c:0},
  {q:"What planet is Rey from?",a:["Jakku","Tatooine","Corellia","Endor"],c:0},
  {q:"What is Kylo Ren's real name?",a:["Ben Solo","Jacen Solo","Cade Skywalker","Anakin Solo"],c:0},
  {q:"Who is Kylo Ren's father?",a:["Luke","Han Solo","Lando","Wedge"],c:1},
  {q:"What is the name of the Resistance general?",a:["Leia Organa","Holdo","Jyn Erso","Mon Mothma"],c:0},
  {q:"Which planet contains Starkiller Base?",a:["Ilum","Exegol","Crait","Jedha"],c:0},
  {q:"Who builds the Death Star?",a:["Geonosians","Hutts","Bothans","Chiss"],c:0},
  {q:"What planet has the red salt surface?",a:["Crait","Hoth","Ilum","Jedha"],c:0},
  {q:"What was Din Djarin's original ship called?",a:["Razor Crest","Falcon","Ghost","Slave I"],c:0},
  {q:"What is the child of Yoda's species called in The Mandalorian?",a:["Grogu","Yaddle","Minch","Oteg"],c:0},
  {q:"What is the Rebel base in Rogue One called?",a:["Yavin 4","Hoth","Endor","Dantooine"],c:0},
  {q:"Who steals the Death Star plans?",a:["Jyn Erso","Leia","Cassian","Bodhi"],c:0},
  {q:"What is the name of the pilot in Rogue One?",a:["Bodhi Rook","Poe Dameron","Wedge","Biggs"],c:0},
  {q:"What is the name of the Imperial scientist in Rogue One?",a:["Galen Erso","Krennic","Tarkin","Hux"],c:0},
  {q:"Who is Director Krennic?",a:["Death Star director","Jedi","Rebel","Smuggler"],c:0},
  {q:"What is the planet Jedha known as?",a:["Holy Jedi world","Hutt planet","Clone planet","Imperial capital"],c:0},
  {q:"Which creatures live on Endor?",a:["Ewoks","Jawas","Tusken Raiders","Wookiees"],c:0},
  {q:"Who leads the Ewoks?",a:["Wicket","Logray","Chirpa","Paploo"],c:2},
  {q:"What is the Mandalorian capital called?",a:["Sundari","Keldabe","Concordia","Krownest"],c:0},
  {q:"Who rules Mandalore in The Clone Wars?",a:["Duchess Satine","Bo-Katan","Ursa","Sabine"],c:0},
  {q:"Who kills Satine?",a:["Maul","Obi-Wan","Dooku","Vader"],c:0},
  {q:"What species is Jar Jar?",a:["Gungan","Rodian","Toydarian","Kaminoan"],c:0},
  {q:"What species is Watto?",a:["Toydarian","Rodian","Hutt","Twi'lek"],c:0},
  {q:"What species is Jabba?",a:["Hutt","Gamorrean","Trandoshan","Nikto"],c:0},
  {q:"Who is Jabba's dancer?",a:["Oola","Leia","Ayla","Lyn"],c:0},
  {q:"What is Boba Fett's ship called?",a:["Slave I","Razor Crest","Ghost","Falcon"],c:0},
  {q:"What is the name of Jango Fett's son?",a:["Boba","Cade","Rex","Fenn"],c:0},
  {q:"Who is Captain Rex?",a:["Clone","Jedi","Sith","Smuggler"],c:0},
  {q:"What type is Anakin's starfighter?",a:["Eta-2","X-Wing","A-Wing","Y-Wing"],c:0},
  {q:"What fighter does Luke fly?",a:["X-Wing","A-Wing","TIE","B-Wing"],c:0},
  {q:"What are Imperial fighters called?",a:["TIE Fighter","ARC","Z95","V-Wing"],c:0},
  {q:"What is Palpatine's Sith name?",a:["Darth Sidious","Darth Tyranus","Darth Bane","Darth Nihilus"],c:0},
  {q:"What is the name of the creature in the Sarlacc pit?",a:["Sarlacc","Rancor","Krayt Dragon","Exogorth"],c:0},
  {q:"Which planet is home to the Tusken Raiders?",a:["Tatooine","Jakku","Geonosis","Jedha"],c:0},
  {q:"Who is the commander of the Rebel fleet at the Battle of Endor?",a:["Admiral Ackbar","Mon Mothma","Jan Dodonna","Wedge Antilles"],c:0},
  {q:"What species is Bossk?",a:["Trandoshan","Rodian","Weequay","Nikto"],c:0},
  {q:"What is the name of Han Solo's blaster?",a:["DL-44","E-11","DC-15","SE-14"],c:0},
  {q:"Which planet is known for its floating Cloud City?",a:["Bespin","Corellia","Ord Mantell","Bracca"],c:0},
  {q:"Who betrays Han Solo to Darth Vader on Bespin?",a:["Lando Calrissian","Boba Fett","Wedge Antilles","Biggs Darklighter"],c:0},
  {q:"Which Jedi survives Order 66 and later appears in Rebels?",a:["Kanan Jarrus","Kit Fisto","Plo Koon","Saesee Tiin"],c:0},
  {q:"What is the name of Hera Syndulla's ship?",a:["Ghost","Phantom","Razor Crest","Outrider"],c:0},
  {q:"Which species is Grand Admiral Thrawn?",a:["Chiss","Mirialan","Zabrak","Pantoran"],c:0},
  {q:"What is the name of Luke Skywalker's callsign during the Death Star attack?",a:["Red Five","Gold Leader","Blue Seven","Rogue One"],c:0},
  {q:"Which Jedi Master has a green lightsaber and a long beard in Episode I?",a:["Qui-Gon Jinn","Ki-Adi-Mundi","Plo Koon","Saesee Tiin"],c:0},
  {q:"Which droid says 'Roger, roger'?",a:["B1 Battle Droid","BX Commando Droid","Droideka","KX Droid"],c:0},
  {q:"What creature pulls the sled on Hoth for the Rebels?",a:["Tauntaun","Bantha","Dewback","Varactyl"],c:0},
  {q:"Who is the Supreme Leader before Kylo Ren?",a:["Snoke","Palpatine","Hux","Thrawn"],c:0},
  {q:"What is the name of the Jedi Temple planet?",a:["Coruscant","Ilum","Jedha","Tython"],c:0},
  {q:"Which bounty hunter wears a breathing mask and bandages?",a:["Dengar","Bossk","IG-88","Zuckuss"],c:0},
  {q:"What species is Greedo?",a:["Rodian","Aqualish","Trandoshan","Nikto"],c:0},
  {q:"Which planet do the Jawas live on?",a:["Tatooine","Jakku","Ryloth","Jedha"],c:0},
  {q:"Who cuts off Anakin's arm in Episode II?",a:["Count Dooku","Obi-Wan Kenobi","Mace Windu","Yoda"],c:0},
  {q:"Which Jedi fights General Grievous on Utapau?",a:["Obi-Wan Kenobi","Anakin Skywalker","Kit Fisto","Mace Windu"],c:0},
  {q:"What species is Kit Fisto?",a:["Nautolan","Mon Calamari","Quarren","Kel Dor"],c:0},
  {q:"What is the name of the Jedi with the long cone-shaped head?",a:["Ki-Adi-Mundi","Plo Koon","Shaak Ti","Saesee Tiin"],c:0},
  {q:"Which planet is Obi-Wan from?",a:["Stewjon","Coruscant","Alderaan","Corellia"],c:0},
  {q:"Which creature does Obi-Wan ride on Utapau?",a:["Varactyl","Tauntaun","Bantha","Reek"],c:0},
  {q:"Which Jedi Master trains Count Dooku?",a:["Yoda","Windu","Qui-Gon","Kenobi"],c:0},
  {q:"What is the name of the Nightsister leader on Dathomir?",a:["Mother Talzin","Ventress","Merrin","Shaak Ti"],c:0},
  {q:"What species is Asajj Ventress?",a:["Dathomirian","Zabrak","Mirialan","Twi'lek"],c:0},
  {q:"What is the name of the Mandalorian weapon that can counter lightsabers?",a:["Darksaber","Beskar Spear","Electrostaff","Vibroblade"],c:0},
  {q:"Who originally created the Darksaber?",a:["Tarre Vizsla","Pre Vizsla","Bo-Katan","Din Djarin"],c:0},
  {q:"What metal is Mandalorian armor typically made from?",a:["Beskar","Durasteel","Cortosis","Phrik"],c:0},
  {q:"What is the capital city of Naboo?",a:["Theed","Otoh Gunga","Keren","Moenia"],c:0},
  {q:"Which senator later becomes the Emperor?",a:["Palpatine","Bail Organa","Mon Mothma","Padmé"],c:0},
  {q:"What species are the guards of Jabba's palace?",a:["Gamorreans","Nikto","Weequay","Aqualish"],c:0},
  {q:"Which creature guards Jabba's dungeon?",a:["Rancor","Sarlacc","Wampa","Acklay"],c:0},
  {q:"What is the name of the protocol droid in The Mandalorian who protects Grogu?",a:["IG-11","IG-88","K-2SO","AP-5"],c:0},
  {q:"What is the name of the blue milk animal on Tatooine?",a:["Bantha","Nerf","Tauntaun","Dewback"],c:0},
  {q:"Which Jedi uses two blue lightsabers in Attack of the Clones?",a:["Anakin Skywalker","Obi-Wan Kenobi","Kit Fisto","Plo Koon"],c:0},
  {q:"Which Sith rule limits them to two members?",a:["Rule of Two","Rule of Shadows","Rule of the Sith","Rule of Balance"],c:0},
  {q:"Who established the Sith Rule of Two?",a:["Darth Bane","Darth Revan","Darth Malak","Darth Plagueis"],c:0},
  {q:"Which planet is known for spice mining prisons?",a:["Kessel","Corellia","Rodia","Nal Hutta"],c:0},
  {q:"Which alien species pilots pod racers on Tatooine?",a:["Various species","Only humans","Only Toydarians","Only Rodians"],c:0},
  {q:"What is the name of Anakin's podracer rival in Episode I?",a:["Sebulba","Watto","Dud Bolt","Gasgano"],c:0},
  {q:"What species is Sebulba?",a:["Dug","Rodian","Toydarian","Aqualish"],c:0},
  {q:"What is the name of the Republic starfighter used in Clone Wars?",a:["ARC-170","X-Wing","TIE Fighter","Z-95"],c:0},
  {q:"Which planet hosts the Jedi temple where younglings train?",a:["Coruscant","Ilum","Tython","Jedha"],c:0},
  {q:"What is the name of the red Imperial guards protecting the Emperor?",a:["Royal Guard","Praetorian Guard","Shadow Guard","Sentinel Guard"],c:0},
  {q:"Which Jedi Master has horns and red skin?",a:["Darth Maul","Eeth Koth","Savage Opress","Darth Talon"],c:1},
  {q:"What species is Plo Koon?",a:["Kel Dor","Nautolan","Ithorian","Chiss"],c:0},
  {q:"Which Rebel pilot destroys the shield generator on Endor?",a:["Han Solo","Wedge Antilles","Lando Calrissian","Luke Skywalker"],c:0}
];
